[package]
name = "async-imap"
version = "1.0.0"
authors = ["dignifiedquire <me@dignifiedquire.com>",
           "Matt McCoy <mattnenterprise@yahoo.com>",
           "Jon Gjengset <jon@thesquareplanet.com>"]
documentation = "https://docs.rs/imap/"
repository = "https://github.com/jonhoo/rust-imap"
homepage = "https://github.com/jonhoo/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"
edition = "2018"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "jonhoo/rust-imap" }
is-it-maintained-open-issues = { repository = "jonhoo/rust-imap" }

[features]
default = []

[dependencies]
regex = "1.0"
imap-proto = { version = "0.9.0", git = "https://github.com/dignifiedquire/tokio-imap", branch = "async-imap"}
nom = "5.0"
base64 = "0.10"
chrono = "0.4"
lazy_static = "1.4"
async-tls = { git = "https://github.com/async-rs/async-tls" }
async-std = { git = "https://github.com/async-rs/async-std", features = ["unstable"] }
pin-utils = "0.1.0-alpha.4"
futures_codec = "0.3"
bytes = "0.4.12"
futures = "0.3.0"
async-attributes = "1.1.0"
rental = "0.5.5"

[dev-dependencies]
lettre = "0.9"
lettre_email = "0.9"
rustls-connector = "0.8.0"
rustls = { version = "0.16.0", features = ["dangerous_configuration"] }
native-tls = "0.2.3"
webpki = "0.21.0"

[[example]]
name = "basic"
required-features = ["default"]

[[example]]
name = "gmail_oauth2"
required-features = ["default"]

[[test]]
name = "imap_integration"
required-features = ["default"]


[patch.'https://github.com/async-rs/async-std']
async-std = { path = "../async-std" }