[package]
name = "imap"
version = "1.0.2"
authors = ["dignifiedquire <me@dignifiedquire.com>",
           "Matt McCoy <mattnenterprise@yahoo.com>",
           "Jon Gjengset <jon@thesquareplanet.com>"]
documentation = "https://docs.rs/imap/"
repository = "https://github.com/jonhoo/rust-imap"
homepage = "https://github.com/jonhoo/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"
edition = "2018"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
azure-devops = { project = "jonhoo/jonhoo", pipeline = "imap", build = "11" }
codecov = { repository = "jonhoo/rust-imap", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "jonhoo/rust-imap" }
is-it-maintained-open-issues = { repository = "jonhoo/rust-imap" }

[features]
default = []

[dependencies]
regex = "1.0"
imap-proto = "0.9.0"
nom = "5.0"
base64 = "0.10"
chrono = "0.4"
lazy_static = "1.4"
async-tls = "0.5.0"
async-std = { git = "https://github.com/async-rs/async-std", features = ["unstable"] }
pin-utils = "0.1.0-alpha.4"
futures_codec = { git = "https://github.com/dignifiedquire/futures-codec", branch = "imap" }
bytes = "0.4.12"
futures-preview = "0.3.0-alpha.19"
async-attributes = "1.1.0"

[dev-dependencies]
lettre = "0.9"
lettre_email = "0.9"
rustls-connector = "0.8.0"

[[example]]
name = "basic"
required-features = ["default"]

[[example]]
name = "gmail_oauth2"
required-features = ["default"]

[[test]]
name = "imap_integration"
required-features = ["default"]
